# .github/workflows/feature_cleanup.yml

name: Feature Branch Cleanup

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  cleanup:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Delete feature branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
